{"tag": "info", "depth": 0, "time": 1587484471.6014097, "data": {"name": "Final Error", "traceback": "Traceback (most recent call last):\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\cli\\runner.py\", line 61, in runTest\n    exec(compile(code.encode(\"utf-8\"), pyfilepath, 'exec'), self.scope)\n  File \"E:\\demo\\airtest_auto\\air_case\\\u6253\u5f00\u6211\u7684\u6587\u7ae0.air\\\u6253\u5f00\u6211\u7684\u6587\u7ae0.py\", line 8, in <module>\n    poco = AndroidUiautomationPoco(use_airtest_input=True, screenshot_each_action=False)\n  File \"E:\\app\\python37\\lib\\site-packages\\poco\\drivers\\android\\uiautomation.py\", line 173, in __init__\n    self.ime.start()\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\core\\android\\ime.py\", line 108, in start\n    self.yosemite.get_ready()\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\utils\\snippet.py\", line 105, in ready_func\n    method()\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\core\\android\\yosemite.py\", line 22, in install_or_upgrade\n    self._install_apk_upgrade(YOSEMITE_APK, YOSEMITE_PACKAGE)\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\core\\android\\yosemite.py\", line 40, in _install_apk_upgrade\n    self.adb.install_app(apk_path, replace=True, install_options=[\"-t\", \"-g\"])\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 571, in install_app\n    out = self.cmd(cmds)\n  File \"E:\\app\\python37\\lib\\site-packages\\airtest\\core\\android\\adb.py\", line 194, in cmd\n    raise AdbError(stdout, stderr)\nairtest.core.error.AdbError: stdout[] stderr[adb: failed to install E:\\app\\python37\\lib\\site-packages\\airtest\\core\\android\\static\\apks\\Yosemite.apk: ]\n"}}
